field: bab1985a-1b08-45aa-b667-ef3a1b3422a8
fieldLayouts:
  0783aa5f-8578-45fb-b5eb-94a66fc46a77:
    tabs:
      -
        elements:
          -
            fieldUid: fd6a9b0b-c68e-4add-bb6f-217e308b32a0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  fd6a9b0b-c68e-4add-bb6f-217e308b32a0:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:91bf635a-721b-4687-8fc4-f34564d38616'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:91bf635a-721b-4687-8fc4-f34564d38616'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
