fieldLayouts:
  07adb3b8-661a-44ac-9fdb-3707a25bd41f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  331c97fc-d7b2-41c3-9371-7965dee11a7f:
    hasUrls: true
    template: blog/_category
    uriFormat: 'blog-categories/{slug}'
structure:
  maxLevels: 1
  uid: 61b69ee4-dc7e-4f53-ae0f-17fe5534633c
