contentColumnType: string
fieldGroup: a20ec7da-3fd3-42c1-8c78-65856ca5eb67
handle: aboutImage
instructions: ''
name: 'About Image'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:966af62a-b1f6-4d0c-bb07-72ef8d017f43'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:91bf635a-721b-4687-8fc4-f34564d38616'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:966af62a-b1f6-4d0c-bb07-72ef8d017f43'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
