contentColumnType: string
fieldGroup: d32ba746-906b-4d53-aef8-8ea88f43f008
handle: featureImage
instructions: 'Feature Image'
name: 'Feature Image'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:91bf635a-721b-4687-8fc4-f34564d38616'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add a feature image '
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:91bf635a-721b-4687-8fc4-f34564d38616'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
