fieldLayouts:
  dd0c49fc-e069-4926-89a5-c8c426a645ef:
    tabs:
      -
        elements:
          -
            fieldUid: 251e1c98-3ff8-4a33-aa86-2ee67486bef3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
