enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  331c97fc-d7b2-41c3-9371-7965dee11a7f:
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
